<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DIKERMA</AssemblyName>
    <RootNamespace>Dikerma.Windows</RootNamespace>
    <Version>0.2.0</Version>
    <ApplicationIcon>Assets/AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets/AppIcon.ico" />
    <PackageReference Include="PDFsharp-wpf" Version="6.2.4" />
  </ItemGroup>
</Project>
